TALHA MAZHAR

In [2]:
2+3+9

14

In [4]:
100/7

14.285714285714286

In [5]:
100//7

14

In [6]:
100 % 7

2

### VARIABLE

In [ ]:
my_fav_color_is = "Red"

In [ ]:
my_fav_color_is 

In [ ]:
color1,color2,color3 = "Blue","green","pink"

In [9]:
color1

NameError: name 'color1' is not defined

In [4]:
def filter(number_list):
    Even_no=[]
    for number in number_list:
        if number % 2 == 0:
            Even_no.append(number)
    return Even_no

In [5]:
filter([1,2,3,4,5,6,7,8,9])


[2, 4, 6, 8]

In [ ]:
w1,w2,w3= 0.3,0.2,0.5

In [6]:
w1,w2,w3= 0.3,0.2,0.5
Kanto_temp = 73
Kanto_rainfall = 67
Kanto_humidity = 43
Kanto_yield_apple= Kanto_temp * w1 + Kanto_rainfall * w2 + Kanto_humidity * w3
print("The expected yield of apples in Kanto region is {} tons per hectare".format(Kanto_yield_apple))

The expected yield of apples in Kanto region is 56.8 tons per hectare


In [21]:
kanto = [73,67,43]
johto = [91,88,64]
hoenn = [87,134,58]
sinnoh = [102,43,37]
unova =[69,96,70]

weights = [w1,w2,w3]

def crop_yield (region,weights):
    results= 0
    for x,w in zip (region,weights):
        results = results + x*w
    return results


In [22]:
crop_yield(kanto,weights)

56.8

In [15]:
crop_yield(johto,weights)

76.9

In [16]:
crop_yield(unova,weights)

74.9

In [ ]:
import numpy as np

In [ ]:
kanto = [73,67,43]

In [24]:
import numpy as np
kanto=np.array([73, 67, 43])

In [26]:
kanto

array([73, 67, 43])

In [27]:

weights = np.array([w1,w2,w3])

In [29]:
type(weights)

numpy.ndarray

In [30]:
weights[1]

0.2

In [31]:
np.dot(kanto,weights)

56.8

In [32]:
(kanto*weights).sum()

56.8

In [36]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr1 * arr2



array([ 4, 10, 18])

In [41]:
arr1= list(range(100000))
arr2= list(range(100000,200000))

arr1_np= np.array(arr1)
arr2_np= np.array(arr2)

results = 0
for x1,x2 in zip(arr1,arr2):
    results += x1*x2
results


833323333350000

In [48]:
arr1= list(range(100000))
arr2= list(range(100000,200000))

arr1_np= np.array(arr1)
arr2_np= np.array(arr2)

np.dot(arr1_np,arr2_np)

893678192

In [51]:
climate_data= np.array([[73, 67, 43],
                         [91, 88, 64],
                         [87, 134, 58],
                         [102, 43, 37],
                         [69, 96, 70]])



In [52]:
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [55]:
climate_data.shape

(5, 3)

In [56]:
weights.shape

(3,)

In [58]:
arr3 = np.array([
    [[11, 12, 13], 
     [13, 14, 15]], 
    [[15, 16, 17], 
     [17, 18, 19.5]]])

arr3.shape

(2, 2, 3)

In [59]:
np.matmul(climate_data,weights)

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [60]:
climate_data @ weights

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [9]:
import numpy as np

arr2 = np.array([[1, 2, 3, 4], 
                 [5, 6, 7, 8], 
                 [9, 1, 2, 3]])

arr2.shape

(3, 4)

In [10]:
arr4 = np.array([4, 5, 6, 7])

In [11]:
arr2+arr4

array([[ 5,  7,  9, 11],
       [ 9, 11, 13, 15],
       [13,  6,  8, 10]])

In [14]:
import numpy as np

arr1 = np.array([[1, 2, 3], [3, 4, 5]])
arr2 = np.array([[2, 2, 3], [1, 2, 5]])
arr1 == arr2
arr1 > arr2

array([[False, False, False],
       [ True,  True, False]])

In [15]:
arr1 > arr2

array([[False, False, False],
       [ True,  True, False]])

In [16]:
arr1 < arr2

array([[ True, False, False],
       [False, False, False]])

In [17]:
(arr1 == arr2).sum()

3

In [20]:
import numpy as np

arr3 = np.array([
    [[11, 12, 13, 14], 
     [13, 14, 15, 19]], 
    
    [[15, 16, 17, 21], 
     [63, 92, 36, 18]], 
    
    [[98, 32, 81, 23],      
     [17, 18, 19.5, 43]]])

arr3[1,0,3]

21.0

In [21]:
arr3[1,1,3]

18.0

In [22]:
import numpy as np


### Basic Numpy Arrays

In [24]:
array1= np.array([1,2,3,4])

In [25]:
array1

array([1, 2, 3, 4])

In [44]:
a=np.array([1,2,3,4,5,6,7,8])
b=np.array([0, .5, 1, 1.5, 2])

In [28]:
a[3],b[2]

(4, 1.0)

In [29]:
c=a[3],b[2]
c

(4, 1.0)

In [31]:
a[0:]

array([1, 2, 3, 4])

In [32]:
a[1:3]

array([2, 3])

In [42]:
a[1:-1]

array([2, 3])

In [ ]:
a[::2]

In [46]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [47]:
b[0],b[2],b[-1]

(0.0, 1.0, 2.0)

In [49]:
b[[0,2,-1]]

array([0., 1., 2.])

### Array Type

In [50]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [52]:
a.dtype

dtype('int32')

In [53]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [54]:
b.dtype

dtype('float64')

In [60]:
np.array([1, 2, 3, 4], dtype=float)

array([1., 2., 3., 4.])

In [64]:
np.array([1, 2, 3, 4], dtype=int)

array([1, 2, 3, 4])

In [65]:
c =np.array(["a","b","c"])

In [66]:
c.dtype

dtype('<U1')

In [70]:
import sys
d=np.array([{"a":1}.sys])

AttributeError: 'dict' object has no attribute 'sys'

In [71]:
d.dtype

dtype('O')

### Dimensions and shapes

In [73]:
A = np.array([[1,2,3],
             [4,5,6]])

In [75]:
A.shape

(2, 3)

In [76]:
A.ndim

2

In [77]:
A.size

6

In [83]:
B=np.array([[[12,11,10],
            [9,8,7]],
           
           [[6,5,4],
            [3,2,1]]])

In [84]:
B.shape

(2, 2, 3)

In [86]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [88]:
B.ndim

3

In [89]:
B.size

12

In [ ]:
C = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4]
    ]
])

In [91]:
C.dtype

NameError: name 'C' is not defined

In [92]:
type(c[0])

numpy.str_

### Indexing and Slicing of Matrices

In [93]:
# Square Matrix
A= np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])

In [94]:
A[1]

array([4, 5, 6])

In [95]:
A[1][0]

4

In [96]:
A[1,0]

4

In [98]:
A[0:2]

3

In [99]:
A[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [100]:
A[:2,:2]

array([[1, 2],
       [4, 5]])

In [101]:
A[:2,2:]

array([[3],
       [6]])

In [102]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [103]:
A[1]=np.array([10,10,10])

In [104]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [105]:
A[2]=99

In [106]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

### Summary statistics

In [113]:
A=np.array([[ 1,  2,  3],
            [10, 11, 12],
            [69, 79, 89]])

In [114]:
A

array([[ 1,  2,  3],
       [10, 11, 12],
       [69, 79, 89]])

In [115]:
A[1].sum()

33

In [117]:
A[2].mean()

79.0

In [118]:
A.std()

34.70190516703978

In [119]:
A.sum()

276

In [120]:
A.mean()

30.666666666666668

In [121]:
A.std()

34.70190516703978

In [122]:
A.sum(axis=0)

array([ 80,  92, 104])

In [123]:
A.sum(axis=1)

array([  6,  33, 237])

In [124]:
A.mean(axis=0)

array([26.66666667, 30.66666667, 34.66666667])

In [125]:
A.mean(axis=1)

array([ 2., 11., 79.])

In [ ]:
A.mean(axis=2)

### Broadcasting and Vectorized operations

In [129]:
a=np.arange(4)

In [130]:
a

array([0, 1, 2, 3])

In [131]:
a +10

array([10, 11, 12, 13])

In [132]:
a * 10

array([ 0, 10, 20, 30])

In [133]:
a

array([0, 1, 2, 3])

In [134]:
a +=100

In [135]:
a

array([100, 101, 102, 103])

In [ ]:
l =[0,1,2,3]

In [142]:
l =[0,1,2,3]
[i * 10 for i in l]


[0, 10, 20, 30]

In [150]:
a=np.arange(4)

In [151]:
a

array([0, 1, 2, 3])

In [152]:
b=np.array([10,10,10,10])

In [153]:
b

array([10, 10, 10, 10])

In [154]:
a + b

array([10, 11, 12, 13])

In [155]:
a * b

array([ 0, 10, 20, 30])

In [156]:
a[[True,False,False,True]]

array([0, 3])

In [157]:
a

array([0, 1, 2, 3])

In [158]:
 a>=2

array([False, False,  True,  True])

In [159]:
a[a>=2]

array([2, 3])

In [160]:
a.mean()

1.5

In [161]:
a[ a> a.mean()]

array([2, 3])

In [163]:
a[~( a> a.mean())]

array([0, 1])

In [164]:
a[( a== 0) | (a==1)]

array([0, 1])

In [168]:
a[( a <= 2) & (a % 2 == 0)]

array([0, 2])

In [170]:
A=np.random.randint(100,size=(3,3))

In [172]:
A

array([[69, 18, 43],
       [56,  9, 90],
       [29, 36, 21]])

In [173]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([69, 43,  9, 29, 21])

In [174]:
A > 30

array([[ True, False,  True],
       [ True, False,  True],
       [False,  True, False]])

In [175]:
A[A>30]

array([69, 43, 56, 90, 36])

In [ ]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])



In [178]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [179]:
A.dot(B)

array([[572, 442],
       [552, 397],
       [360, 274]])

In [180]:
A @ B

array([[572, 442],
       [552, 397],
       [360, 274]])

In [181]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [182]:
A

array([[69, 18, 43],
       [56,  9, 90],
       [29, 36, 21]])

In [183]:
B.T @ A

array([[696, 216, 660],
       [542, 153, 506]])

In [185]:
sys.getsizeof(1)

28

In [186]:
sys.getsizeof(10*100)

28

In [187]:
sys.getsizeof(10**100)

72

In [190]:
np.dtype(np.int8).itemsize

1

In [191]:
l= list(range(100000))

In [193]:
a =np.arange(100000)

In [194]:
a

array([    0,     1,     2, ..., 99997, 99998, 99999])

In [195]:
%time np.sum(a**2)

CPU times: total: 0 ns
Wall time: 68 ms


216474736

In [196]:
sum([x**2 for x in l])

333328333350000